-- AlterTable
ALTER TABLE "EditorOverlay" ADD COLUMN     "zIndex" INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE "EditorProject" ADD COLUMN     "fps" INTEGER NOT NULL DEFAULT 30,
ADD COLUMN     "height" INTEGER NOT NULL DEFAULT 720,
ADD COLUMN     "width" INTEGER NOT NULL DEFAULT 1280;
